name: Tree minute doc
description: File a bug report
title: "[Project]: "
labels: ["scope", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
   - type: markdown
    attributes:
      value: |
        Use this form to create a tree minute paper about this project
   - type: checkboxes
    id: isNew
    attributes:
      label: First time interacting with stackspot?
      options:
        - label: Yes
          required: false
  - type: dropdown
    id: type
    attributes:
      label: Type of project
      description: 
      options:
        - Studio
        - Stack
        - Plugin
        - Poc
        - Talk
    validations:
      required: true
  - type: textarea
    id: whatisit
    attributes:
      label: What is it?
      description: How can we describe this project?
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: goals
    attributes:
      label: What are the goals?
      description: what we can expect as a result of this project?
      placeholder: 
    validations:
      required: true
 
